### ISSUE TITLE
Capturing too slow?

### ISSUE THREAD

**Issue by MusicalPulse** [dj-kata/sdvx_helper#12]
Hi, sorry for the English. You can ignore my issue if you don't understand.

I am trying to use this for a home arcade cabinet for private streams. I think I set it up correctly, but the capture.png seems to capture too slow or maybe the arcade cabinet loads faster than konasute. It always looks like this:

![select_jacket](https://github.com/dj-kata/sdvx_helper/assets/13542365/1426d9a7-ffb0-48cd-ac9c-53dccedb858d)

Any help is appreciated!

Machine translation:

機械翻訳：

こんにちは。もし理解できないのであれば、私の問題を無視しても構いません。

私はプライベートストリーム用の家庭用アーケードキャビネットにこれを使おうとしています。正しくセットアップしたつもりなのですが、capture.pngのキャプチャが遅すぎるのか、アーケード筐体のロードがkonasuteより速いようです。いつもこんな感じです：

![select_jacket](https://github.com/dj-kata/sdvx_helper/assets/13542365/1426d9a7-ffb0-48cd-ac9c-53dccedb858d)

どんな助けでもありがたい！

**Comment by dj-kata** [comment]
Thank you for your report!

The performance on capturing is a known issue of OBS websocket.
It has a possibility that the performance is improved by using another API.
You can use this settings by disabling "画面取得時にファイル保存を行う(旧方式)" on setting dialog.
When you configure like this, this tool get captures without saving it to the storage (processed on memory).
![image](https://github.com/dj-kata/sdvx_helper/assets/61326119/d0ae6daf-f750-4e55-8d58-80ffd448e6bb)

However, this method may not work under some CPUs.

btw, Are you trying to use this tool for SDVX arcade version?
I debugged it with only konasute ver, so that it might not work on arcade ver due to a slight difference on game UI.

I wish this tool will work well on your PC...

**Comment by MusicalPulse** [comment]
Hi, thank you for your reply.

I tried unchecking that option, but then what source do I use for OBS then since nowplaying.html doesn't update anymore?

Some other questions: Whenever i click 'save' here (am i supposed to?) this happens: https://i.imgur.com/BeSbx2Q.png
and then crashes, even if i run with administrator. 

Do i need to 'set' anything else here? https://i.imgur.com/WQBr2sr.png

Thank you!


お返事ありがとうございます。

そのオプションのチェックを外してみたのですが、そうするとnowplaying.htmlが更新されなくなるので、OBSのソースは何を使えばいいのでしょうか？

他にもいくつか質問があります： https://i.imgur.com/BeSbx2Q.png。
と表示され、管理者で実行してもクラッシュしてしまいます。

https://i.imgur.com/WQBr2sr.png。

ありがとうございました！

**Comment by dj-kata** [comment]
> https://imgur.com/BeSbx2Q
It seems that there is a problem concerned with premission of directory.
I guess it fails in reading/writing a setting file(settings.json) and in saving captures.
Did you install this tool in Desktop (or other directories on C drive)?

I have no idea why it doesn't work when running it with administrator...., but can you install sdvx_helper somewhere other than C drive? (e.g. D drive)

**Comment by MusicalPulse** [comment]
I installed it on C drive, since my stream computer only has 1 drive.
I will try my other PC to test.

私のストリームコンピュータにはドライブが1つしかないので、Cドライブにインストールした。
他のPCでテストしてみます。

**Comment by MusicalPulse** [comment]
Sorry, I didn't get an answer for what source I should be using in OBS. After unchecking that option, nowplaying.html doesn't update anymore, is this normal?

すみません、OBSでどのソースを使うべきかの答えが得られませんでした。このオプションのチェックを外した後、nowplaying.htmlが更新されなくなったのですが、これは正常なのでしょうか？

**Comment by MusicalPulse** [comment]
Here is what happened testing on other PC. It doesn't give me that permission error when pressing 'save', but only when 画面取得時にファイル保存を行う(旧方式) is checked.

When I try to uncheck and then press 'save', the program will freeze and become unresponsive.

他のPCでテストした結果です。保存'を押してもパーミッションエラーは出ないが、画面取得時にファイル保存(旧方式)を行うとエラーが出る。

チェックを外して保存を押すと、プログラムがフリーズして反応しなくなる。

**Comment by dj-kata** [comment]
Thanks for verifying.
I will check whether there might be a bug around on-memory capturing function.

**Comment by dj-kata** [comment]
By the way, if you **don't** check 画面取得時にファイル保存を行う(旧方式) on that PC, does it still not work due to the same problem as top of this thread?

**Comment by MusicalPulse** [comment]
Unfortunately I'm unable to test arcade data on my regular PC because I do not have a SDVX controller right now. I will try to test more on arcade cabinet using a second drive tomorrow.

残念ながら、SDVXコントローラーを持っていないので、普段使っているPCでアーケードのデータをテストすることができないんだ。明日、セカンドドライブを使ってアーケード筐体でもっとテストしてみるつもりだ。

**Comment by dj-kata** [comment]
Thank you for your cooperation.
In konasute SDVX, we can select songs with keyboard (cursor and Enter keys).

Or, Are you by any chance installing this tool on an Arcade Edition PC? If so, it might be equipped with a special-purpose version of Windows, so there may be compatibility issues with the x64 instruction set, etc.

**Comment by MusicalPulse** [comment]
I am not using konasute. I am using it for a arcade cabinet, but I have it connected to my laptop with a capture card for streaming. The laptop is the one that is running OBS when i stream, so i am trying to use sdvx_helper there. Hopefully that makes sense.

On my main PC I only tested if it had the permission error or not.

Thanks a lot for your help and patience. <3

私はkonasuteを使っていません。アーケードキャビネットに使っているのですが、ストリーミング用にキャプチャカードでラップトップに接続しています。ストリーミングの際にOBSを動かしているのはラップトップなので、そこでsdvx_helperを使おうとしています。うまくいけばいいのですが。

メインのPCでは、パーミッションエラーが出るかどうかだけテストしました。

ご協力と忍耐に感謝します。<3

**Comment by dj-kata** [comment]
I checked around the on-memory capturing function and found no problems.
We should solve the permission problem on your streaming PC.

**Comment by MusicalPulse** [comment]
I was working with someone else that got it working with arcade cabinet.

I solved the permission issue by selecting a different folder inside C drive for the screenshots. Normally I think it is trying to save straight into C:\ directory which may cause problems. The other person also replicated the permission error.

However, the program seems to not be recognizing plays when old method on-memory option is checked.

capture.png is updating but program stays stuck at 1 play and mode:init.

When I uncheck it seems to recognize everything, (play count will go up and mode will update) but nowplaying.html has not been updating since yesterday when I first tried unchecking the memory option. We suspect maybe it is a Windows 11 problem, because the person I am talking to has it working on Windows 10.

I was working with someone else that got it working with arcade cabinet.

I solved the permission issue by selecting a different folder inside C drive for the screenshots. Normally I think it is trying to save straight into C:\ directory which may cause problems. The other person also replicated the permission error.

However, the program seems to not be recognizing plays when old method on-memory option is checked.

capture.png is updating but program stays stuck at 1 play and mode:init.

When I uncheck it seems to recognize everything, (play count will go up and mode will update) but nowplaying.html has not been updating since yesterday when I first tried unchecking the memory option. We suspect maybe it is a Windows 11 problem, because the person I am talking to has it working on Windows 10.

私は、アーケードキャビネットで動作するようにした他の人と一緒に仕事をしていました。

私は、スクリーンショット用にCドライブ内の別のフォルダを選択することで、パーミッションの問題を解決しました。通常、私はそれが問題を引き起こすかもしれないC:³³ディレクトリにまっすぐに保存しようとしていると思います。他の人もパーミッションエラーを再現していました。

しかし、old method on-memory オプションがチェックされている場合、プログラムはプレイを認識しないようです。

capture.pngは更新されていますが、プログラムは1プレイとmode:initで止まったままです。

チェックを外すとすべてを認識するようですが（再生回数は増え、モードも更新されます）、nowplaying.htmlは、メモリオプションのチェックを外してみた昨日から更新されていません。Windows 11の問題ではないかと疑っています。というのも、私が話している相手はWindows 10で動作しているからです。

**Comment by MusicalPulse** [comment]
Here is a separate error that pops up sometimes when trying to change settings.

これは、設定を変更しようとしたときに時々現れる別のエラーです。


https://i.imgur.com/oCMJwLy.png

OBSに接続しました
** Error looking up your element using the key:  txt_mode The closest matching key:  None
Exception in thread Thread-30 (detect):
Traceback (most recent call last):
  File "PySimpleGUI\PySimpleGUI.py", line 10423, in find_element
KeyError: 'txt_mode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "sdvx_helper.pyw", line 967, in detect
  File "sdvx_helper.pyw", line 627, in control_obs_sources
  File "PySimpleGUI\PySimpleGUI.py", line 11705, in __getitem__
  File "PySimpleGUI\PySimpleGUI.py", line 10429, in find_element
  File "PySimpleGUI\PySimpleGUI.py", line 20938, in _error_popup_with_traceback
  File "PySimpleGUI\PySimpleGUI.py", line 20957, in _error_popup_with_code
  File "PySimpleGUI\PySimpleGUI.py", line 10079, in read
  File "PySimpleGUI\PySimpleGUI.py", line 10150, in _read
  File "PySimpleGUI\PySimpleGUI.py", line 9890, in _Show
  File "PySimpleGUI\PySimpleGUI.py", line 16942, in StartupTK
  File "tkinter\__init__.py", line 1458, in mainloop
RuntimeError: Calling Tcl from different apartment

**Comment by MusicalPulse** [comment]
It seems to work after a new install. I unchecked the old on-memory option and nowplaying does update, but it is still too slow. It looked like it wasn't updating to me because it captures the same loading screen every time.

https://i.imgur.com/db7zlzd.jpeg

新規インストール後はうまくいくようだ。古いオンメモリオプションのチェックを外したところ、nowplayingは更新されるようになったが、それでも遅すぎる。毎回同じローディング画面をキャプチャするので、私には更新されていないように見えた。

https://i.imgur.com/db7zlzd.jpeg

**Comment by dj-kata** [comment]
The development and verification of this tool was done on Windows 10, so there may be problems with Windows 11...

**Comment by dj-kata** [comment]
I have one idea, if the problem is that you are building on Windows 10, installing Python3 for Windows, downloading the source code of sdvx_helper and running the sdvx_helper.pyw may improve the situation.

However, this workaround may be difficult because you will need to install the pip packages yourself... (e.x., ```py -m pip install PySimpleGUI``` at Command Prompt)

**Comment by UMRPL** [comment]
Since this is opened I will add that Ive tried tool with my cabinet and arcade version(using separate PC to stream)
Now playing doesn't work properly and I am sure it's because AC version loads faster on premium mode so program doesn't manage to catch up.
But in summary play title of song and score showed properly. Konaste version takes 5 sec to load that's why helper can catch it but AC takes maybe 1-2 sec

**Comment by dj-kata** [comment]
Thank you for helpful information. I didn't know the difference on transition time between konasute and arcade.

In settings.json, you can modify the sleep time for updating nowplaying.html in "detect_wait". The nowplaying.html maybe work when you decrease this value (nearly 0?)

**Comment by MusicalPulse** [comment]
That fixes it! Thanks so much.

**Comment by MusicalPulse** [comment]
One more question, is there any way to use summary.png without having to click 'save' every song?

**Comment by MusicalPulse** [comment]
Here's an error I get sometimes when clicking 'save'. Program stops working after the error

Exception in thread Thread-6 (detect):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "sdvx_helper.pyw", line 994, in detect
  File "sdvx_helper.pyw", line 627, in control_obs_sources
  File "PySimpleGUI\PySimpleGUI.py", line 3774, in update
  File "tkinter\__init__.py", line 402, in set
RuntimeError: main thread is not in main loop
