### ISSUE TITLE
Webhook Name uses player name in settings|ウェブフック名は、設定のプレーヤー名を使用

### ISSUE THREAD

**Issue by ARealDuck** [dj-kata/sdvx_helper#16]
When setting the webhook name to be used for display in discord it takes the player name entry in the settings rather than having its own entry set to it. this means that if you wanted to have a seperate name for the webhook. you have to deal with the name showing up in places like sdvx_stats.html the easiest way to fix it would be to set a completely seperate entry in the settings to pull from and edit into for that specifically. When I get the time ill see about making that change into my own fork of the repository and if no issues arise from the change ill send a pull request through.

TL:
discordでの表示に使用するWebhook名を設定する際、独自のエントリを設定するのではなく、設定のプレイヤー名エントリを使用します。 つまり、ウェブフックに別の名前を付けたい場合、その名前がsdvx_stats.htmlのような場所に表示されることに対処しなければなりません。それを解決する最も簡単な方法は、プルする設定に完全に別のエントリーを設定し、それ専用に編集することです。時間ができたら、その変更を自分のリポジトリのフォークに反映させ、その変更によって問題が生じなければ、プルリクエストを送ろうと思っている。

**Comment by dj-kata** [comment]
OK, I will add a new parameter for name when sending webhooks.

**Comment by dj-kata** [comment]
I will add ```webhook_player_name``` in manage_settings.py. (BAD variable name... but I have no better idea...)

```
    # カスタムwebhook用
    # それぞれ1エントリが1つの設定に対応。(全ての配列が同じ長さになる)
    'webhook_player_name':'', # webhook送信時のプレーヤ名(元のplayer_nameと独立させるために追加)
    'webhook_names':[], # 1entry: 説明文(str)
    'webhook_urls':[], # 1entry: url(str)
    'webhook_enable_pics':[], # 1entry:bool (画像を送信するかどうか)
    'webhook_enable_lvs':[], # 1entry:[False,False,...True]のような長さ20の配列(lv1-20)
    'webhook_enable_lamps':[], # 1entry:[True,True,False,False,False] puc,uc,hard,clear,failed
```

**Comment by dj-kata** [comment]
I fixed like above in 805ba22.
This commit will be included in the next release.

**Comment by dj-kata** [comment]
This feature is included in [v.1.0.21](https://github.com/dj-kata/sdvx_helper/releases/tag/v.1.0.21).
