### ISSUE TITLE
Add third option to screen orientation (Rotating through Windows display settings)

### ISSUE THREAD

**Issue by RDBomber** [dj-kata/sdvx_helper#18]
Currently, sdvx_helper allows for two orientations.
These are 90 and 270 degrees rotated respectively. 
Or, as the setting is called, `top_is_right` in managed_settings.py and sdvx_helper.pyw.
This setting is used in `get_capture_after_rotate` in sdvx_helper.pyw.

There are nothing wrong with these options.

However, there are use cases where the player may need to show other types of content on stream, such as pulling up a view of a SDVX chart, videos or clips of SDVX, pull up clear/scoring tierlists, or simply needs to alt-tab (switch out) of the game to check something.
 
However, since they aren't rotated through the game, but rather through the display settings in Windows, sdvx_helper can't be used because the game is already rotated, and sdvx_helper can't parse it like this.

My suggestion is to add a third option to this setting, where the user indicates they aren't rotating it through the launcher settings for SDVX. (Attached images for reference of settings of the setup mentioned.)
![image](https://github.com/user-attachments/assets/43aac03f-a8e2-4bf6-b0d6-ba2027b7a79b)

![image](https://github.com/user-attachments/assets/5b7c6ebc-efd6-43dd-ade6-9f5e3873cc94) 

The user may still need to add a game capture source for sdvx_helper to use and work as intended, but for those other types of content, they can still use another scene with a display capture source for their needs, and helper will switch back to said scenes whenever it's triggered.

It would also probably be ideal to name this setting something different if this is changed. Maybe something like `display_orientation` ?

Thank you for your work on this project, it has been helpful for automatic scene switching and rivals.

**Comment by dj-kata** [comment]
Sorry for the delay in replying.
I see that you want to rotate the screen in Windows settings, not konasute sdvx, and specify the orientation of the attached image in sdvx setting.
This may be difficult to do just now, but I will consider it.

**Comment by mat3osz** [comment]
Adding simple boolean "Use rotation" and if yes -> ret = img.rotate(90, expand=True), else "" could fix the issue and do not require changes to logic behind rotation (also boolean value). 
I couldn't build it also, there are modules that I can't install with pip

**Comment by dj-kata** [comment]
Thanks to mat3osz via twitter, a solution to this problem was revealed.
We are releasing v.1.0.29 which includes the fixes at  4b4eefdcc1c.

**Comment by dj-kata** [comment]
Sorry for the delay! v.1.0.29 has been released.
