### ISSUE TITLE
一日のプレイ曲数をcsvでグーグルドライブに保存

### ISSUE THREAD

**Issue by Buuta101** [dj-kata/sdvx_helper#9]
ボルテの公式サイトで確認できるプレー回数のように自分が一日にプレイした曲数が保存できる
機能があればうれしいです
A列　　　　　　　B列
2024年1月8日　　20
2024年1月9日　　50
2024年1月10日　 60

こんな感じで保存されてると嬉しいです

**Comment by dj-kata** [comment]
[v.1.0.20](https://github.com/dj-kata/sdvx_helper/releases/tag/v.1.0.20)で対応しました。

playcount.csvというファイル名で、以下のように自動保存されます。
![image](https://github.com/dj-kata/sdvx_helper/assets/61326119/3ec4c3cb-a706-4746-aa6a-a987119a3654)

**Comment by Buuta101** [comment]
対応ありがとうございます！
